### ISSUE TITLE
Exclude Armature modifier from being applied when applying modifiers with shapes (gret) and reducing to two meshes

### ISSUE THREAD

**Issue by mistyskye** [Mysteryem/AvatarBuilder#6]
First, I just want to say this is an amazing tool for improving model export workflow! Thanks for this.

I've ran into an issue/suggestion that I think could benefit other people:
In my model, I have standard meshes (no shapekeys), and Head, Eyes and other meshes which have shapekeys, various modifiers (e.g. subdiv) and an armature modifier.
I've selected `Reduce to two meshes` so that the Head + Eyes etc join together separately from everything else. 
I've also changed Apply modifiers to `Apply with shapes (gret)` on the meshes with shapekeys.

Unfortunately, this means that once I build the avatar, the final Head object loses the Armature node. I'm not sure if this is a bug or if it's intentional, in which case I was wondering if you could add a checkbox to ignore Armature node in Apply modifiers.

This is a small issue as I can add the Armature node afterwards and it works as long as I uncheck `Remove non-deform` to keep the vertex groups. In terms of automation though, adding this could be really helpful for me!

**Comment by Mysteryem** [comment]
Hmm, by Armature node I'm guessing you're talking about the Armature Modifier?

If your version of gret is older that 0.1.0, it looks like it by default deletes all the modifiers that aren't applied, I'll change my code so that the default value isn't used and it instead always keeps the modifiers that aren't applied.
It looks like I need to fix some things for gret 1.0.0 and newer, so I'd recommend you try upgrading to gret 0.3.1, since that should be the newest working version with Avatar Builder.

Otherwise...

Applying modifiers should only apply non-armature modifiers. I couldn't reproduce this issue here.

Make sure your Armature Modifier is enabled in the viewport. Disabled modifiers are currently removed from Builds.

Additionally, make sure that the mesh the other shape key meshes get joined into has all the modifiers you need, since when Blender joins meshes together, the resultant mesh will only have the modifiers of the one mesh all the other meshes were joined into. If you're joining meshes manually with `ctrl+j` or `Object>Join`, this would be whichever of the selected meshes is the active object.

The way Avatar Builder picks the 'active object' when joining meshes together is by choosing the mesh with the lowest `Join Order`. If there's a tie, it will pick whichever mesh has the most shape keys and if there's still a tie, it will pick the first object alphabetically.

**Comment by mistyskye** [comment]
Yes, I meant Armature modifier, not sure why I wrote that in the title! I've now fixed the title.

Thanks for your reply. I was using gret 0.1 as I wasn't sure which version would work with Blender 2.93. 

I've just installed 0.3.1 and the armature modifier stays on my Head object after building the avatar! So this wasn't an issue with your add-on, more of a user error.
